# ansible-playbook uptime.yml --inventory inventory
---
- hosts: all

  tasks:
    - name: Show the uptime in days/hours/minutes/seconds
      ansible.builtin.debug:
        msg: Uptime {{ now().replace(microsecond=0) - now().fromtimestamp(now(fmt='%s') | int - ansible_uptime_seconds) }}
